In [84]:
!pip install catboost
!pip install joblib

Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.25.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (2.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.50.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (1.3.2)

In [66]:
import pandas as pd
import seaborn as sns

In [67]:
df = pd.read_csv('https://raw.githubusercontent.com/SPUTnik-42/BadalBarsaBijuli/master/Dataset_BBB.csv')
df

,Date,Location,MinimumTemperature,MaximumTemperature,Rainfall,Evaporation,Sunshine,WindGustDirection,WindGustSpeed,WindDirection9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temperature9am,Temperature3pm,CloudBurst Today,CloudBurstTomorrow
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,21-06-2017,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,22-06-2017,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,23-06-2017,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,24-06-2017,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,25-06-2017,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [68]:
df = df.dropna()

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                56420 non-null  object
 1   Location            56420 non-null  object
 2   MinimumTemperature  56420 non-null  float64
 3   MaximumTemperature  56420 non-null  float64
 4   Rainfall            56420 non-null  float64
 5   Evaporation         56420 non-null  float64
 6   Sunshine            56420 non-null  float64
 7   WindGustDirection   56420 non-null  object
 8   WindGustSpeed       56420 non-null  float64
 9   WindDirection9am    56420 non-null  object
 10  WindDirection3pm    56420 non-null  object
 11  WindSpeed9am        56420 non-null  float64
 12  WindSpeed3pm        56420 non-null  float64
 13  Humidity9am         56420 non-null  float64
 14  Humidity3pm         56420 non-null  float64
 15  Pressure9am         56420 non-null  float64
 16  Pressure3pm         56420 non-null  float64
 17  Cloud9am            56420 non-null  float64
 18  Cloud3pm            56420 non-null  float64
 19  Temperature9am      56420 non-null  float64
 20  Temperature3pm      56420 non-null  float64
 21  CloudBurst Today    56420 non-null  object
 22  CloudBurstTomorrow  56420 non-null  object
dtypes: float64(16), object(7)
memory usage: 10.3+ MB

In [70]:
#removing uneccessary columns
df = df.drop(['Date','Location','Evaporation','Rainfall','Sunshine','WindGustDirection','WindDirection9am','WindDirection3pm','WindSpeed9am','Humidity9am','Pressure9am','Cloud9am','Temperature9am','CloudBurst Today','Temperature3pm'], axis=1)
df

,MinimumTemperature,MaximumTemperature,WindGustSpeed,WindSpeed3pm,Humidity3pm,Pressure3pm,Cloud3pm,CloudBurstTomorrow
6049,17.9,35.2,48.0,20.0,13.0,1004.4,5.0,No
6050,18.4,28.9,37.0,19.0,8.0,1012.1,1.0,No
6052,19.4,37.6,46.0,15.0,22.0,1009.2,6.0,No
6053,21.9,38.4,31.0,6.0,22.0,1009.1,5.0,No
6054,24.2,41.0,35.0,13.0,15.0,1007.4,6.0,No
...,...,...,...,...,...,...,...,...
142298,19.3,33.4,35.0,20.0,32.0,1010.5,1.0,No
142299,21.2,32.6,37.0,11.0,28.0,1011.2,0.0,No
142300,20.7,32.8,33.0,11.0,23.0,1011.8,0.0,No
142301,19.5,31.8,26.0,17.0,58.0,1010.7,1.0,No
142302,20.2,31.7,30.0,7.0,32.0,1009.7,5.0,No

In [72]:
df['CloudBurstTomorrow'].replace({'No': 0, 'Yes': 1},inplace = True)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MinimumTemperature  56420 non-null  float64
 1   MaximumTemperature  56420 non-null  float64
 2   WindGustSpeed       56420 non-null  float64
 3   WindSpeed3pm        56420 non-null  float64
 4   Humidity3pm         56420 non-null  float64
 5   Pressure3pm         56420 non-null  float64
 6   Cloud3pm            56420 non-null  float64
 7   CloudBurstTomorrow  56420 non-null  int64
dtypes: float64(7), int64(1)
memory usage: 3.9 MB

In [75]:
features = df[['MinimumTemperature','MaximumTemperature','WindGustSpeed','WindSpeed3pm','Humidity3pm','Pressure3pm','Cloud3pm']]
target = df['CloudBurstTomorrow']

# Split into test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.25, random_state=42)

In [76]:
import time
from sklearn.metrics import accuracy_score, roc_auc_score, cohen_kappa_score, roc_curve, classification_report
def run_model(model, X_train, y_train, X_test, y_test, verbose=True):
    t0=time.time()
    if verbose == False:
        model.fit(X_train,y_train, verbose=0)
    else:
        model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred)
    coh_kap = cohen_kappa_score(y_test, y_pred)
    time_taken = time.time()-t0
    print("Accuracy = {}".format(accuracy))
    print("ROC Area under Curve = {}".format(roc_auc))
    print("Cohen's Kappa = {}".format(coh_kap))
    print("Time taken = {}".format(time_taken))
    print(classification_report(y_test,y_pred,digits=5))

    probs = model.predict_proba(X_test)
    probs = probs[:, 1]
    fper, tper, thresholds = roc_curve(y_test, probs)



    return model, accuracy, roc_auc, coh_kap, time_taken

In [77]:
import catboost as cb
params_cb ={'iterations': 50,
            'max_depth': 16}

model_cb = cb.CatBoostClassifier(**params_cb)
model_cb, accuracy_cb, roc_auc_cb, coh_kap_cb, tt_cb = run_model(model_cb, X_train, y_train, X_test, y_test, verbose=False)

Accuracy = 0.8434597660404112
ROC Area under Curve = 0.721884220658097
Cohen's Kappa = 0.4944544563523202
Time taken = 85.13593101501465
              precision    recall  f1-score   support

           0    0.86931   0.94025   0.90339     10979
           1    0.70583   0.50352   0.58775      3126

    accuracy                        0.84346     14105
   macro avg    0.78757   0.72188   0.74557     14105
weighted avg    0.83308   0.84346   0.83343     14105

In [78]:
import requests

city_name = "Dehradun"
api_key = '5e5d431b17906d316dc226222b1047aa'
url = f'http://api.openweathermap.org/data/2.5/weather?q={city_name}&units=metric&appid={api_key}'
response = requests.get(url)
data = response.json()
temp_min = data['main']['temp_min']
temp_max = data['main']['temp_max']
humidity = data['main']['humidity']
pressure = data['main']['pressure']
wind_speed = data['wind']['speed']
wind_gust = data['wind']['gust']
clouds = data['clouds']['all']

print(temp_min,temp_max,humidity,pressure,wind_speed,wind_gust,clouds)
data

30.19 30.19 9 1004 4.06 2.79 1

{'coord': {'lon': 78.0437, 'lat': 30.3256},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 30.19,
  'feels_like': 28.31,
  'temp_min': 30.19,
  'temp_max': 30.19,
  'pressure': 1004,
  'humidity': 9,
  'sea_level': 1004,
  'grnd_level': 911},
 'visibility': 10000,
 'wind': {'speed': 4.06, 'deg': 260, 'gust': 2.79},
 'clouds': {'all': 1},
 'dt': 1712400585,
 'sys': {'type': 1,
  'id': 9162,
  'country': 'IN',
  'sunrise': 1712363445,
  'sunset': 1712408955},
 'timezone': 19800,
 'id': 1273313,
 'name': 'Dehradun',
 'cod': 200}

In [82]:
input_data = pd.DataFrame({
    'MinimumTemperature': [temp_min],
    'MaximumTemperature': [temp_max],
    'WindGustSpeed':wind_gust,
    'WindSpeed3pm': [wind_speed],
    'Humidity3pm': [humidity],
    'Pressure3pm': [pressure],
    'Cloud3pm': [clouds]
})
input_data

,MinimumTemperature,MaximumTemperature,WindGustSpeed,WindSpeed3pm,Humidity3pm,Pressure3pm,Cloud3pm
0,30.19,30.19,2.79,4.06,9,1004,1

In [83]:
predictions = model_cb.predict(input_data)
predictions

array([0])

In [85]:
import joblib
joblib.dump(model_cb, 'model_bbb.joblib', compress=('zlib', 3))

['model_bbb.joblib']